services:
  database:
    image: timescale/timescaledb:latest-pg15
    container_name: climate-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app
    env_file:
      - ./.env
volumes:
  postgres_data:

networks:
  app: